  version: '3.8'

  services:

    db:
      image: postgres:latest
      container_name: travelers
      restart: always
      volumes:
        - ./db/sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
        - ./db/sql/data.sql:/docker-entrypoint-initdb.d/data.sql
      environment:
        - POSTGRES_DB=travelers
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
      ports:
        - "5432:5432"
